### ISSUE TITLE
DNS aktualisieren

### ISSUE THREAD

**Issue by caugner** [bleibtoffen/bleibtoffen-dns#1]
@datendelphin @giggls Könnt ihr bitte das DNS gemäß 9ab194837b64238f2a85ed9a3351f85368197ad4 aktualisieren?

**Comment by caugner** [comment]
@giggls Sobald du die Einladung zur Organisation angenommen hast, kann ich dir auch Issues zuweisen. :-)

**Comment by giggls** [comment]
Ich finde keine Einladung.

**Comment by caugner** [comment]
> Ich finde keine Einladung.

Hm, du solltest [laut Hilfe](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/inviting-collaborators-to-a-personal-repository) eine E-Mail erhalten haben, vermutlich an die in GitHub hinterlegte "primary email address".

**Comment by giggls** [comment]
Habs im GUI gefunden müsste jetzt drin sein.

**Comment by caugner** [comment]
Leider war ich etwas voreilig, besser wäre es, wenn die `CNAME`s auf `aperta.fr.` zeigen (statt direkt auf den Server).

(Aperta ist der neue internationale Name von "Ca reste ouvert".)

**Comment by caugner** [comment]
Danke euch!

> * https://www.whatsmydns.net/#CNAME/www.bleibtoffen.at
> * https://www.whatsmydns.net/#CNAME/www.bleibtoffen.ch
> * https://www.whatsmydns.net/#CNAME/www.bleibtoffen.de
