### ISSUE TITLE
Weiterleitung nach www

### ISSUE THREAD

**Issue by caugner** [bleibtoffen/bleibtoffen-dns#2]
Wir bräuchten eine Weiterleitung vom Second-Level auf `www.`, vgl.: https://github.com/bleibtoffen/bleibtoffen-dns/commit/9ab194837b64238f2a85ed9a3351f85368197ad4#commitcomment-38340116

@datendelphin @giggls Wie machen wir das am besten?

**Comment by datendelphin** [comment]
mach ich über die sosm server (in progress) für die ch, at und org

**Comment by giggls** [comment]
Dann brauche ich IP-Adressen für A und ggfs. AAAA-records, korrekt?

**Comment by datendelphin** [comment]
wenn du die .de auch gleich über den sosm server laufen lassen willst, dann kannst du 95.128.36.189 eintragen

**Comment by caugner** [comment]
Ihr seid großartig! 🚀

**Comment by giggls** [comment]
Sonst müsste ich auf einem meienr server einen redirect machen. Besser einheitlich.

**Comment by caugner** [comment]
@giggls Habe die A-Records in 02470c40386ee2d8aa4224149e7822fc25bfc97e ergänzt.

**Comment by caugner** [comment]
Die Weiterleitungen von `bleibtoffen.{at,ch}` kann ich nachvollziehen:

```terminal
$ curl -sI bleibtoffen.at
HTTP/1.1 301 Moved Permanently
Date: Tue, 07 Apr 2020 12:22:23 GMT
Server: Apache/2.4.18 (Ubuntu)
Location: https://www.bleibtoffen.at
Content-Type: text/html; charset=iso-8859-1

$ curl -sI bleibtoffen.ch
HTTP/1.1 301 Moved Permanently
Date: Tue, 07 Apr 2020 12:22:36 GMT
Server: Apache/2.4.18 (Ubuntu)
Location: https://www.bleibtoffen.ch
Content-Type: text/html; charset=iso-8859-1
```

@datendelphin Evtl. im Apache noch [`ServerTokens Major`](https://httpd.apache.org/docs/2.4/mod/core.html#servertokens) setzen? Aktuell ist [2.4.43](https://downloads.apache.org/httpd/CHANGES_2.4).

**Comment by giggls** [comment]
Wird halt ein Ubuntu LTS sein :)

`bleibtoffen.de` geht auch (wenn nicht ist halt noch das alte DNS gecached).

```bash
 ~/ > curl -sI bleibtoffen.de
HTTP/1.1 301 Moved Permanently
Date: Tue, 07 Apr 2020 12:27:01 GMT
Server: Apache/2.4.18 (Ubuntu)
Location: https://www.bleibtoffen.de
Content-Type: text/html; charset=iso-8859-1
```

**Comment by caugner** [comment]
Hast Recht:

* https://launchpad.net/apache2/+packages (16.04 LTS => 2.4.18)
* https://www.whatsmydns.net/#A/bleibtoffen.de

Danke euch, schließe das Issue hiermit.

**Comment by giggls** [comment]
Ich Ende bei einem falschen Zertifikat.
osc-fr1.scalingo.io und *.osc-fr1.scalingo.io

**Comment by caugner** [comment]
Ja, das ist auf französischer Seite noch nicht vollständig eingerichtet.
